---
title: "SC-HW3"
author: 
- 'ID : 111024517'
- 'Name : 鄭家豪'
date: due on 04/03
geometry: left=3cm,right=3cm,top=2cm,bottom=2cm
header-includes:
  - \usepackage{leading}
  - \leading{18pt}
  - \usepackage{xeCJK}
  - \setCJKmainfont{標楷體}
  - \setCJKmonofont{標楷體}
output:
  pdf_document:
    latex_engine: xelatex
classoption: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment = "")
```

# Power function for Alternative Model II
Jarque-Bera(JB) test statistic:
$$
\text{JB} = \frac{n}{6}(\text{skewness}^2+\frac{1}{4}(\text{kurtosis-3})^2),
$$
where
$$
\begin{split}
&\text{skewness} =\dfrac{\frac{1}{n-1}\sum^{n}_{i=1}(X_i-\bar{X})^3}{s^3} \\
&\text{kurtosis}=\dfrac{\frac{1}{n-1}\sum^{n}_{i=1}(X_i-\bar{X})^4}{s^4}\\
&\text{,where }s^2 = \frac{1}{n-1}\sum^{n}_{i=1}(X_i-\bar{X})^2.
\end{split}
$$
Setting:

* Alternative model II: $t(v)$ with df $v=1/\theta,0<\theta\leq1$.
* $\theta=(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)$.
* Replication M=10000
* $\alpha=0.05$.

## (a) data with size n = 20
For each $\theta_i$,the testing results:  
```{r}
JB <- function(sample){
  n = length(sample)
  skew_upp <- sum((sample-mean(sample))^3)/(n-1)
  skew <- skew_upp/(sd(sample))^3
  kurt_upp <- sum((sample-mean(sample))^4)/(n-1)
  kurt <- kurt_upp/(sd(sample))^4
  return(n/6*(skew^2+1/4*(kurt-3)^2))
} # JB depend on sample
experiment7 = function(n, theta){
  x = rt(n, df=1/theta)
  JB(x)
} #generate JB
n = 20 # small
M = 10000 #MC replication
reject.rate = rep(0,9)
testing.result = matrix(, nrow = 9, ncol = 2)
testing.result = as.data.frame(testing.result)
colnames(testing.result) <- c("non-reject","reject")
sd.MC <- rep(0,9)
the <- c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)
set.seed(1)
for (i in 1:9){
  y = replicate(M, experiment7(n,theta=the[i]))
  testing.result[i,] <- c(table((y >qchisq(p = 0.95,df = 2))))
  reject.rate[i] = mean(y >qchisq(p = 0.95,df = 2)) 
  sd.MC[i] <- sqrt(reject.rate[i]*(1-reject.rate[i])/M)
}
theta_col <-  paste0("theta","=",seq(0.1, 0.9, length=9))
knitr::kable(cbind(theta_col,testing.result,reject.rate,sd.MC),
             col.names = c("","non-reject","reject","reject.rate","sd.MC"))
```

## (b) data with size n = 100
For each $\theta_i$,the testing results:  
```{r}
n = 100 # large
reject.rate1 = rep(0,9)
testing.result1 = matrix(, nrow = 9, ncol = 2)
testing.result1 = as.data.frame(testing.result1)
colnames(testing.result1) <- c("non-reject","reject")
sd.MC <- rep(0,9)
set.seed(6)
for (i in 1:9){
  y = replicate(M, experiment7(n,theta =the[i]))
  count = as.vector(table((y >qchisq(p = 0.95,df = 2))))
  testing.result1[i,] <- count
  reject.rate1[i] = mean(y >qchisq(0.95,2))
  sd.MC[i] <- sqrt(reject.rate1[i]*(1-reject.rate1[i])/M)
}
theta_col <-  paste0("theta","=",seq(0.1, 0.9, length=9))
knitr::kable(cbind(theta_col,testing.result1,reject.rate1,sd.MC),
             col.names = c("","non-reject","reject","reject.rate","sd.MC"))
```

## Power function plot
```{r}
par(mfcol=c(1,1))
plot(sort(the),reject.rate,type="b", pch=16, axes=F,
     lwd=2, ylim=c(0,1), 
     xlab="theta", ylab="Power (rejection rate)")
title("Alternative model II: t-dist", line = 1.5)
axis(1, labels = sort(the), at=sort(the))
axis(2)
box()
abline(h=0.05,lty=2,col=2, lwd=2)
lines(sort(the),reject.rate1,
      col=3,lwd=2, pch=16, type="b")
legend(0.65,0.65,legend=c("n=20","n=100","type I error"),
       lty=1, col=c(1,3,2), lwd=2, bty="n")
```

As the sample size increases, power increases significantly.